---
#server:
#  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/masconfig
    username: root
    password: nskZU7yofaNFeIkn2I8pusQNOhHLA6SL
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      pool-name: masdbpool
      minimumIdle: 5
      max-lifetime: 40000
      idle-timeout: 30000
    algorithm: PBEWithMD5AndDES
    word: mas@1logis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB