---
#server:
 # port: 8081
spring:
  datasource:
    url: jdbc:mysql://maslogisticsdb.c7h1wp4abumo.eu-north-1.rds.amazonaws.com:3306/masconfig
    username: masdb
    password: DgKGvAX8+yZaDV/+koKrmybEK4cJtx2u
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      pool-name: masdbpool
      minimumIdle: 5
      max-lifetime: 40000
      idle-timeout: 30000
    algorithm: PBEWithMD5AndDES
    word: mas@1logis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB